apiVersion: v1
kind: Service
metadata:
  name: sit737-task6p-service
spec:
  type: NodePort
  selector:
    app: sit737-task6p-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30036
